#!/usr/bin/env bash
# install load balancer

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # Check if the command exists, if not, install it
    if [ $? -ne 0 ]; then
        echo -e "Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "	${1} is already installed.\n"
    fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up HAProxy configuration...\n"

# Backup the default configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define HAProxy configuration
server_config="
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend main_frontend
    bind *:80
    default_backend main_backend

backend main_backend
    balance roundrobin
    server [STUDENT_ID]-web-01 [web-01-IP]:80 check
    server [STUDENT_ID]-web-02 [web-02-IP]:80 check
"

# Apply the new configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy to start automatically on boot
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy to apply the configuration
if ! pgrep -x "haproxy" > /dev/null; then
    echo "Starting HAProxy service..."
    sudo service haproxy start
else
    echo "Restarting HAProxy service..."
    sudo service haproxy restart
fi

echo -e "HAProxy configuration completed: Round-robin load balancing between web-01 and web-02."

# Output the required strings
echo "web-01"
echo "web-02"
