#!/usr/bin/env bash
# install load balancer

echo -e "Updating and doing some minor checks...\n"

# Function to check and install packages
function install() {
	command -v "$1" &> /dev/null
	if [ $? -ne 0 ]; then
		echo -e "	Installing: $1\n"
		sudo apt-get update -y -qq && \
			sudo apt-get install -y "$1" -qq
		echo -e "\n"
	else
		echo -e "	${1} is already installed.\n"
	fi
}

# Install HAProxy
install haproxy

echo -e "\nSetting up HAProxy configuration.\n"

# Backup default HAProxy config file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Define the new HAProxy configuration
server_config="\
defaults
    mode http
    timeout connect 10s
    timeout client 15s
    timeout server 15s
    timeout http-request 10s

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web01 100.25.190.21:80 check
    server web02 54.160.77.90:80 check
"

# Write the new HAProxy configuration
echo "$server_config" | sudo tee /etc/haproxy/haproxy.cfg > /dev/null

# Enable HAProxy via the init script
echo "ENABLED=1" | sudo tee /etc/default/haproxy > /dev/null

# Restart HAProxy to apply changes
if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy restart
fi

echo -e "HAProxy configuration completed with round-robin load balancing.\n"
