#!/usr/bin/env bash
# This script creates a custom 404 page

# Update the system and install Nginx
sudo apt-get -y update
sudo apt-get install -y nginx

# Set the proper ownership for the web folder and the Nginx configuration
sudo chown -R "$USER":"$USER" /var/www/html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

# Create the index and 404 page
echo "Holberton School for the win!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx to use the custom 404 page
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm 404.html index.nginx-debian.html;
    server_name _;

    # Custom 404 page redirection
    error_page 404 /404.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=-VGIt10m9VQ;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Reload Nginx to apply changes
sudo service nginx reload
